#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandbox
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Sample : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Sample.cshtml"


    public dynamic Model { get; set; }


        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n<html lang=\"ru\">\r\n    <head>\r\n        <meta charset=\"utf-8\"/>\r\n        <title>Т" +
"естовая страница</title>\r\n    </head>\r\n    <body>\r\n        <center><em>");


            
            #line 13 "..\..\Sample.cshtml"
               Write(Model.hello);

            
            #line default
            #line hidden
WriteLiteral("</em></center>\r\n    </body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
